# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_total',
            new_name='shipping_total',
        ),
    ]
