# Generated by Django 2.2.28 on 2025-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant',
            field=models.BooleanField(default=False),
        ),
    ]
